### ISSUE TITLE
Package management primer needed?

### ISSUE THREAD

**Issue by mgalgs** [gophercises/urlshort#8]
It seems like we need a primer on how go handles packages before we can carry out this exercise.

For example, `main.go` is importing `"github.com/gophercises/urlshort"`.  Having tinkered with `go` a bit in the past I know I can `go get` the package and that will download it to `$GOPATH/src/github.com/gophercises/urlshort`.  So should I edit the package there directly?  Or is there some other way of doing local package development?  Seems kind of hacky to edit things in `$GOPATH/src` directly, but maybe that's normal?  I also tried copying it into my project and the compiler complained about finding multiple packages.  I've shuffled things around and got it working but I have no idea if I'm adhering to best practices.

**Comment by joncalhoun** [comment]
Honestly, I'm a little torn here. When I originally created these exercises, I wanted to avoid teaching what I considered the "basics" of Go. Things like "this is a switch statement and this is what it does". I opted to go this route because there are many tutorials out there teaching the basics the goal of this course was to be a stepping stone after a course like that, not an intro to Go.

When I created this exercise how packages work in Go felt like one of those basics, but now I'm not 100% sure.

Give me some time to think about it and try to find a nice happy medium here. I suspect what I'll do is a brief intro to packages in Go and then provide links to read/learn further for anyone who wants to.

In the meantime, here is where I would recommend you start - https://golang.org/doc/code.html#Library
You may want to start higher in the article than where I linked but that is the relevant section on packages in Go I believer.


A brief summary of what I think you need to know would be:

1. All packages are in your `$GOPATH/src` directory (ignoring vendoring for now) and the way you import them is type out exactly what path they are at MINUS the `$GOPATH/src` prefix. There are some projects out there designed to get rid of this requirement, but with standard Go thats how it works.

2. When you `go get` some package (like `github.com/gophercises/urlshort`) it will clone master into that directory + the `$GOPATH/src` prefix. So it ends up grabbing the code from this repo and putting it at `$GOPATH/src/github.com/gophercises/urlshort`. iirc it DOES NOT copy over any VCS stuff so you won't have branches etc. As a result I typically don't edit packages I `go get`.

3. You could instead `git clone` this directory into the same location - `$GOPATH/src/github.com/gophercises/urlshort` - and then you would have VCS and it would work just the same. You could import it in any other Go code you have by importing `github.com/gophercises/urlshort`.

4. When you import a package it uses whatever code is there *right now*. That means it won't check out master and use that if you were hacking on that package, it will use whatever code is in the folder on your local computer right now. Vendoring can be used if you want to "lock" a specific version and [dep](https://github.com/golang/dep) is a good tool for managing dependencies like this.

I think that about sums it up. Let me know if anything is unclear since this will probably be my outline for the brief intro to packages video I do for this exercise 😸

**Comment by mgalgs** [comment]
Got it, totally understand not wanting to get bogged down in the basics.

> I think that about sums it up. Let me know if anything is unclear since this will probably be my outline for the brief intro to packages video I do for this exercise

That summary was wonderful!

**Comment by mgalgs** [comment]
> ignoring vendoring for now

I think this is key.  One reason I was a little unsure on things is because I know there have been lots of changes with go package management in recent years (with vendoring, etc.).

**Comment by joncalhoun** [comment]
Closing this as I don't think it needs any changes at this point.
